AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
  NewCops: enable

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 140

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 25

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: true
  Exclude:
    - app/graphql/types/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  MinSize: 4

Style/WordArray:
  MinSize: 4
