default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reconnect: true
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: resolutionable_dev

test:
  <<: *default
  database: resolutionable_test

production:
  <<: *default
  database: resolutionable
